project_id = "kwmubhjtkdcepexzvmva"

[functions.facebook-pages]
verify_jwt = false

[functions.facebook-publish]
verify_jwt = false

[functions.facebook-cron]
verify_jwt = false

[functions.facebook-setup]
verify_jwt = false

[functions.facebook-refresh]
verify_jwt = false

[functions.instagram-publish]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.generate-video-script]
verify_jwt = false

[functions.generate-ai-video]
verify_jwt = false