project_id = "kwmubhjtkdcepexzvmva"

[functions.facebook-pages]
verify_jwt = false

[functions.facebook-publish]
verify_jwt = false

[functions.facebook-cron]
verify_jwt = false

[functions.facebook-setup]
verify_jwt = false